Repository monsieurbiz/SyliusPluginMaker, pull requests merged in 2024-07, with the labels that each got.

#10 fix(composer): Remove duplicate entry of phpmd/phpmd
  PluginTemplate/composer.json.twig
Labels: quick win

#11 Remove compose files from sylius standard to use the plugin files
  PluginTemplate/Makefile.twig
Labels: Status: needs review, quick win

#13 Clean some files in plugin maker
  PluginTemplate/Makefile.twig
  PluginTemplate/___.github/workflows/recipe.yaml.twig
  PluginTemplate/composer.json.twig
  PluginTemplate/dist/.env.local
  PluginTemplate/dist/config/packages/config_files_filename.yaml.twig
  PluginTemplate/dist/config/routes/config_files_filename.yaml.twig
  PluginTemplate/docker-compose.yaml.dist
  PluginTemplate/phpstan.neon.twig
  PluginTemplate/recipes/1.0-dev/config/packages/config_files_filename.yaml.twig
  PluginTemplate/recipes/1.0-dev/config/routes/config_files_filename.yaml.twig
  PluginTemplate/recipes/1.0-dev/manifest.json.twig
  PluginTemplate/src/Resources/config/routes/shop.yaml
  PluginTemplate/src/Resources/views/.gitkeep
  README.md
  castor.php
Labels: Status: needs review
